eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 0
spring:
    application:
        name: review-server
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${db_password}
        url: jdbc:mysql://localhost:3306/book-hive-app-user-service-db?useSSL=false&createDatabaseIfNotExist=true
        username: ${db_username:root}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
